# Generated by Django 3.2.4 on 2021-06-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('rec_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Bole',
            },
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(max_length=4)),
                ('student_id', models.IntegerField(max_length=8)),
                ('skills', models.CharField(max_length=200)),
                ('job_info', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
