# Generated by Django 3.2.4 on 2021-07-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bole',
            fields=[
                ('phone_num', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('rec_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Bole',
            },
        ),
        migrations.CreateModel(
            name='Job_info',
            fields=[
                ('job_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('job_info', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=50)),
                ('salary', models.FloatField(max_length=10)),
                ('rec_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('phone_num', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('school_info', models.CharField(max_length=25)),
                ('skills', models.CharField(max_length=200)),
                ('internship_job', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
