# Generated by Django 3.2.4 on 2021-06-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('requiremnt', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=50)),
                ('salary', models.FloatField(max_length=10)),
                ('begin_day', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
    ]
