# Generated by Django 3.2.4 on 2021-07-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bole',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('phone_num', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('rec_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Bole',
            },
        ),
        migrations.CreateModel(
            name='Job_info',
            fields=[
                ('company', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('requiremnt', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=50)),
                ('salary', models.FloatField(max_length=10)),
                ('begin_day', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('phone_num', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('school_info', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
