# Generated by Django 3.2.4 on 2021-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bole',
            name='phone_num',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='phone_num',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
